In [5]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [6]:
X, y = load_iris(return_X_y=True)

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [9]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
import numpy as np

(X_train - np.mean(X_train, axis=0)) / np.std(X_train, axis=0)

array([[-0.31786434, -0.33305175, -0.14214484,  0.07930516],
       [-0.31786434, -0.0979564 ,  0.37301095,  0.34365569],
       [-1.0421122 ,  1.31261571, -1.40141454, -1.37462275],
       [-0.92140422,  1.07752036, -1.40141454, -1.37462275],
       [-0.55928029,  0.84242501, -1.22969595, -1.37462275],
       [ 1.0099234 , -0.0979564 ,  0.77368768,  1.4010578 ],
       [-0.31786434, -0.5681471 ,  0.60196908,  1.00453201],
       [ 0.5270915 , -1.74362386,  0.31577142,  0.07930516],
       [-0.43857231, -1.74362386,  0.08681329,  0.07930516],
       [-0.80069624, -0.80324245,  0.02957376,  0.21148042],
       [ 0.16496757,  0.84242501,  0.37301095,  0.47583095],
       [-1.16282017, -0.0979564 , -1.40141454, -1.37462275],
       [-0.31786434, -1.27343315,  0.02957376, -0.18504537],
       [-0.92140422, -1.27343315, -0.48558203, -0.18504537],
       [-0.07644839, -0.80324245,  0.14405282, -0.31722063],
       [ 0.04425959, -0.0979564 ,  0.20129235,  0.34365569],
       [-0.80069624,  2.

In [11]:
X_train_scaled

array([[-0.31786434, -0.33305175, -0.14214484,  0.07930516],
       [-0.31786434, -0.0979564 ,  0.37301095,  0.34365569],
       [-1.0421122 ,  1.31261571, -1.40141454, -1.37462275],
       [-0.92140422,  1.07752036, -1.40141454, -1.37462275],
       [-0.55928029,  0.84242501, -1.22969595, -1.37462275],
       [ 1.0099234 , -0.0979564 ,  0.77368768,  1.4010578 ],
       [-0.31786434, -0.5681471 ,  0.60196908,  1.00453201],
       [ 0.5270915 , -1.74362386,  0.31577142,  0.07930516],
       [-0.43857231, -1.74362386,  0.08681329,  0.07930516],
       [-0.80069624, -0.80324245,  0.02957376,  0.21148042],
       [ 0.16496757,  0.84242501,  0.37301095,  0.47583095],
       [-1.16282017, -0.0979564 , -1.40141454, -1.37462275],
       [-0.31786434, -1.27343315,  0.02957376, -0.18504537],
       [-0.92140422, -1.27343315, -0.48558203, -0.18504537],
       [-0.07644839, -0.80324245,  0.14405282, -0.31722063],
       [ 0.04425959, -0.0979564 ,  0.20129235,  0.34365569],
       [-0.80069624,  2.

In [12]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [13]:
X_train_scaled

array([[0.36111111, 0.375     , 0.44067797, 0.5       ],
       [0.36111111, 0.41666667, 0.59322034, 0.58333333],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.30555556, 0.58333333, 0.11864407, 0.04166667],
       [0.66666667, 0.41666667, 0.71186441, 0.91666667],
       [0.36111111, 0.33333333, 0.66101695, 0.79166667],
       [0.55555556, 0.125     , 0.57627119, 0.5       ],
       [0.33333333, 0.125     , 0.50847458, 0.5       ],
       [0.25      , 0.29166667, 0.49152542, 0.54166667],
       [0.47222222, 0.58333333, 0.59322034, 0.625     ],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.36111111, 0.20833333, 0.49152542, 0.41666667],
       [0.22222222, 0.20833333, 0.33898305, 0.41666667],
       [0.41666667, 0.29166667, 0.52542373, 0.375     ],
       [0.44444444, 0.41666667, 0.54237288, 0.58333333],
       [0.25      , 0.875     , 0.08474576, 0.        ],
       [0.66666667, 0.41666667,

In [14]:
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OrdinalEncoder

In [19]:
data = fetch_openml('adult', version=1, as_frame=True, parser='auto').frame

In [20]:
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country,class
0,2,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,<=50K
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,0,United-States,<=50K
2,2,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,2,United-States,<=50K
3,3,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,2,United-States,<=50K
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,2,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,2,United-States,<=50K
48838,4,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,2,United-States,<=50K
48839,2,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,3,United-States,<=50K
48840,2,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,2,0,2,United-States,<=50K


In [21]:
from sklearn.preprocessing import OneHotEncoder

In [22]:
data.occupation.value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [24]:
import pandas as pd

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

encoded_values = encoder.fit_transform(data[['occupation', 'race']])

new_cols = encoder.get_feature_names_out(['occupation', 'race'])

In [25]:
new_cols

array(['occupation_Adm-clerical', 'occupation_Armed-Forces',
       'occupation_Craft-repair', 'occupation_Exec-managerial',
       'occupation_Farming-fishing', 'occupation_Handlers-cleaners',
       'occupation_Machine-op-inspct', 'occupation_Other-service',
       'occupation_Priv-house-serv', 'occupation_Prof-specialty',
       'occupation_Protective-serv', 'occupation_Sales',
       'occupation_Tech-support', 'occupation_Transport-moving',
       'occupation_nan', 'race_Amer-Indian-Eskimo',
       'race_Asian-Pac-Islander', 'race_Black', 'race_Other',
       'race_White'], dtype=object)

In [28]:
df_encoded = pd.DataFrame(encoded_values, columns=new_cols, index = data.index)

In [30]:
data_final = pd.concat(
    [data.drop(columns=['occupation', 'race']), df_encoded],
    axis = 1
)

In [31]:
data_final

,age,workclass,fnlwgt,education,education-num,marital-status,relationship,sex,capitalgain,capitalloss,...,occupation_Protective-serv,occupation_Sales,occupation_Tech-support,occupation_Transport-moving,occupation_nan,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White
0,2,State-gov,77516,Bachelors,13,Never-married,Not-in-family,Male,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2,Private,215646,HS-grad,9,Divorced,Not-in-family,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,3,Private,234721,11th,7,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Wife,Female,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,Bachelors,13,Divorced,Not-in-family,Female,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
48838,4,NaN,321403,HS-grad,9,Widowed,Other-relative,Male,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
48839,2,Private,374983,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
48840,2,Private,83891,Bachelors,13,Divorced,Own-child,Male,2,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
